/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_shuttleplay_node_NodeBroker */

#ifndef _Included_net_shuttleplay_node_NodeBroker
#define _Included_net_shuttleplay_node_NodeBroker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_shuttleplay_node_NodeBroker
 * Method:    runNodeJs
 * Signature: (Lnet/shuttleplay/node/NodeContext;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_shuttleplay_node_NodeBroker_runNodeJs
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     net_shuttleplay_node_NodeBroker
 * Method:    debugNodeJs
 * Signature: (Lnet/shuttleplay/node/NodeContext;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_shuttleplay_node_NodeBroker_debugNodeJs
  (JNIEnv *, jclass, jobject, jstring);

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved);

extern JavaVM* gvm;
extern jobject gData;

#ifdef __cplusplus
}
#endif
#endif
